#!/bin/bash

# Update bashrc
cat /config/.bashrc >> ~/.bashrc
# Create ~/bin directory
mkdir -p ~/bin
# Download zellij into ~/bin
cd ~/bin
wget https://github.com/zellij-org/zellij/releases/download/v0.43.1/zellij-x86_64-unknown-linux-musl.tar.gz
tar -xzvf zellij-x86_64-unknown-linux-musl.tar.gz
# Add zellij config.
mkdir -p ~/.config/zellij
cp /config/.config/zellij/config.kdl ~/.config/zellij

# Neovim setup 
cd ~/bin
wget https://github.com/neovim/neovim/releases/download/nightly/nvim-linux-x86_64.tar.gz
tar -xzvf nvim-linux-x86_64.tar.gz
ln -s /root/bin/nvim-linux-x86_64/bin/nvim /root/bin/nvim 
# get the configuration in place
git clone https://github.com/huseyinyilmaz/neovim-config.git ~/.config/nvim
# install rustup
curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y
# install pyenv
curl -fsSL https://pyenv.run | bash
# install starship
curl -sS https://starship.rs/install.sh | sh -s -- --yes --bin-dir=$HOME/bin
# setup starship.
cp /config/.config/starship.toml ~/.config/starship.toml
# install nvm
# Check the repo time to time to see if there is a new version.
# https://github.com/nvm-sh/nvm
curl -o- https://raw.githubusercontent.com/nvm-sh/nvm/v0.40.3/install.sh | bash
